#!/bin/bash

#for fun testing

echo "host for DNS enumeration"
read -p 'Enter Hostname to search ' hostvar
host -t ns $hostvar | cut -d " " -f 4

echo "enter a listed name server from above to attempt zone transfer "
read -p 'Server ' server
host -l $hostvar $server

echo "enter any other possible subdomain or IP address to search "
read -p 'Subdomain ' subvar
host $subvar.$hostvar

echo "enter an IP for basic nmap -Pn scan "
read -p 'IP address ' ip
nmap -Pn $ip

echo "finished"
